### PR TITLE
Update snippetProvider.ts

### PR DESCRIPTION
**Pull request by ThureinOo**
Modify 5 spaces under falsepositives into 4 spaces to fix index errors.

### CODE REVIEW

**Comment by humpalum** [comment]
Thank you!

**Comment by ThureinOo** [comment]
Hi @humpalum , when will it be updated on vscode?
Thanks

**Comment by humpalum** [comment]
Should be up in a few Days. I will add some more features to that version

**Comment by humpalum** [comment]
Its up now. Enjoy :)

**Comment by ThureinOo** [comment]
Thanks brother!

**Pull request merged**
